### 错误处理
抛出异常 => throw err
+ 组织程序的执行
+ 把错误消息打印到控制台 

> 异步的API是无法保证执行顺序的，所以一般情况下只能采用不断回调的方式来进行排序。

为了解决以上编码方式带来的问题，所以在 es6 中新增了一个 API：`Promise`



Promise 基本语法

```javascript
var fs = require('fs')

// 在 EcmaScript 6 语法中新增了一个 API Promise
// Promise 是一个构造函数

// console.log(1)

// 创建一个容器
// 1. 给别人承诺一个 I promise you.
// 		promise 容器一旦创建，就开始执行里面的代码了
var p1 = new Promise(function (resolve, reject) {
	// console.log(2)
	fs.readFile('./data/aa.txt', 'utf8', function (err, data) {
		if (err) {
			// 失败了，承诺容器中的任务失败了。
			// console.log(err)
			// 把容器的 Pending 状态变为失败 Rejected
			reject(err)
		} else {
			// 承诺容器中的任务成功了
			// console.log(data)
			// 把容器的 Pending 状态变为成功 Resolved
			// 也就是说这里调用的 resolve 方法实际上就是 then 方法传递的那个 function
			resolve(data)
		}
	})
})

// console.log(4)
// p1 就是那个承诺
// 当 p1 成功了，然后(then)做指定的操作
// then 方法接受的 function 就是容器中的 resolve 参数
p1
  .then(function (data) {
  		console.log(data)
  }, function (err) {
  		console.log('读取文件失败了', err)
  })
```



封装 Promise 版本的 `readFile`：

```javascript
var fs = require('fs')

function pReadFile (filePath) {
	return new Promise(function (resolve, reject) {
	fs.readFile(filePath, 'utf8', function (err, data) {
		if (err) {
			reject(err)
		} else {
			resolve(data)
		}
	})
})
}

pReadFile('./data/a.txt')
	.then(function (data) {
		console.log(data)
		return pReadFile('./data/b.txt')
	})
	.then(function (data) {
		console.log(data)
		return pReadFile('./data/c.txt')
	})
	.then(function (data) {
		console.log(data)
	})
```

